apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: sabarlabsenv/k6-load-test
        command: ["k6", "run", "/load-test.js"]
      restartPolicy: Never
  backoffLimit: 4
